apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops

commonLabels:
  app: registry

configMapGenerator:
- name: registry-config
  files:
  - config.yml

resources:
- deployment.yaml
- service.yaml
