apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
