apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: javascript-pipeline
  namespace: tekton-worker
spec:
  params:
    - name: git-url
    - name: code-subdir
    - name: git-revision
    - name: build-cmd
    - name: deps-volume
    - name: lease-label
    - name: deploy-host
      type: array
    - name: deploy-dst-dir
  workspaces:
    - name: source-code
    - name: clone-ssh-directory
    - name: upload-ssh-directory
  tasks:
    - name: acquire-lease
      taskRef:
        name: acquire-lease
      params:
        - name: label
          value: $(params.lease-label)
    - name: clone
      taskRef:
        name: git-clone
      runAfter:
        - acquire-lease
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: source-code
        - name: ssh-directory
          workspace: clone-ssh-directory
    - name: build
      taskRef:
        name: npm
      runAfter:
        - clone
      workspaces:
        - name: output
          workspace: source-code
      params:
        - name: build-cmd
          value: $(params.build-cmd)
        - name: path-context
          value: $(params.code-subdir)
        - name: deps
          value: $(params.deps-volume)
    - name: upload
      taskRef:
        name: ssh-client
      runAfter:
        - build
      workspaces:
        - name: output
          workspace: source-code
        - name: ssh-directory
          workspace: upload-ssh-directory
      params:
        - name: sub-dir
          value: $(params.code-subdir)
        - name: dist-dir
          value: dist
        - name: host
          value: ["$(params.deploy-host[*])"]
        - name: dst-dir
          value: $(params.deploy-dst-dir)
    - name: release-lease
      taskRef:
        name: release-lease
      runAfter:
        - build
      params:
        - name: label
          value: $(params.lease-label)
