apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops
namePrefix: prod-

commonLabels:
  app: registry

configMapGenerator:
- name: registry-config
  behavior: replace
  files:
  - config.yml

secretGenerator:
- name: registry-htpasswd
  files:
  - htpasswd
- name: registry-crt
  files:
  - registry.crt
- name: registry-key
  files:
  - registry.key

resources:
- ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/volumes/1
        value: {"secret": {"secretName": "registry-htpasswd"}, "name": "htpasswd"}
      - op: add
        path: /spec/template/spec/volumes/2
        value: {"secret": {"secretName": "registry-crt"}, "name": "registry-crt"}
      - op: add
        path: /spec/template/spec/volumes/3
        value: {"secret": {"secretName": "registry-key"}, "name": "registry-key"}
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/1
        value: {"mountPath": "/etc/docker/registry/htpasswd/", "name": "htpasswd", "readOnly": false}
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/2
        value: {"mountPath": "/etc/docker/registry/ssl-crt/", "name": "registry-crt"}
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/3
        value: {"mountPath": "/etc/docker/registry/ssl-key/", "name": "registry-key"}
    target:
      group: apps
      version: v1
      kind: Deployment
