# modify from https://holly-k-cummins.medium.com/using-lease-resources-to-manage-concurrency-in-tekton-builds-344ba84df297
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: acquire-lease
  namespace: tekton-worker
spec:
  params:
  - name: label
  - name: timeout
    type: string
    default: 20m
  steps:
  - name: create-lease
    image: m.daocloud.io/docker.io/bitnami/kubectl:1.16.3
    script: |
      echo "apiVersion: somegroup.org/v1" > /tmp/lease.yaml
      echo "kind: Lease" >> /tmp/lease.yaml
      echo "metadata:" >> /tmp/lease.yaml
      echo "  name: pipeline-lease-$(inputs.params.label)" >> /tmp/lease.yaml
      echo "  labels:" >> /tmp/lease.yaml
      echo "    app: $(inputs.params.label)" >> /tmp/lease.yaml
      echo -------------------------------------------------
      cat /tmp/lease.yaml
      echo -------------------------------------------------
      kubectl create -f /tmp/lease.yaml || ( echo "Waiting for lease ..." && kubectl wait --for=delete lease.somegroup.org/pipeline-lease-$(inputs.params.label) --timeout=$(inputs.params.timeout) || exit 1 )
      kubectl apply -f /tmp/lease.yaml
