apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ssh-client
  namespace: tekton-worker
spec:
  workspaces:
    - name: output
    - name: ssh-directory
  params:
    - name: sub-dir
      type: string
      default: "."
    - name: dist-dir
      type: string
      default: "dist"
    - name: host
      type: string
    - name: dst-dir
      type: string
    - name: image
      type: string
      default: "docker.io/kroniak/ssh-client:latest"
  steps:
    - name: ssh-client-run
      image: $(params.image)
      workingDir: $(workspaces.output.path)/$(params.sub-dir)/$(params.dist-dir)
      script: |
        #!/usr/bin/env sh
        set -eu
        cp -R $(workspaces.ssh-directory.path) ~/.ssh
        chmod 700 ~/.ssh
        chmod -R 400 ~/.ssh/*
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        ls
        echo
        ssh -i ~/.ssh/id_rsa work@$(params.host) "ls $(params.dst-dir) || mkdir -p $(params.dst-dir)"
        scp -rp . work@$(params.host):$(params.dst-dir)
