apiVersion: v1
kind: Namespace
metadata:
  name: databases
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  namespace: databases
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:7.2.0-alpine
          name: redis
          ports:
            - containerPort: 6379
              name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: databases
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
