apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: databases

commonLabels:
  app: mysql

# generatorOptions:
#   disableNameSuffixHash: true

images:
- name: mysql
  # newName: mysql
  newTag: 8.0.39-debian

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
